config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#home'

  resources :gardens, only: [ :index, :show ] do
    # get 'gardens/:garden_id/plants/new
    resources :plants, only: [ :new, :create ]
  end

  get 'plants/:plant_id/plant_tags/new', to: 'plant_tags#new',    as: 'new_plant_tag'
  post 'plants/:plant_id/plant_tags',    to: 'plant_tags#create', as: 'plant_plant_tags'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
    has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
    belongs_to :garden

    has_many :plant_tags
    has_many :tags, through: :plant_tags
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :tag
  belongs_to :plant
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
    def home
        redirect_to gardens_path
    end
    
    def index
        @gardens = Garden.all
    end
    
    def show
        @garden = Garden.find(params[:id])
        @plants = @garden.plants
        @p_tag  = PlantTag.new
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
    def new
        @garden = Garden.find(params[:garden_id])
        @plant  = Plant.find(params[:plant_id])
        @p_tag  = PlantTag.new
    end

    def create
        @garden = Garden.find(params[:garden_id])
        @plant  = Plant.find(params[:plant_id])

        @tag_ids = params[:plant_tag][:tag_id]
        @tag_ids.each do |id|
            next if id == ""
            PlantTag.create(plant: @plant, tag_id: id)
        end
        

    end

    def create
        plant = Plant.find(params[:plant_id])
        tag = Tag.find(plant_tag_params[:tag])
    
        @p_tag = PlantTag.new(plant: plant, tag: tag)
    
        if @plant_tag.save
          redirect_to garden_path(plant.garden)
        else
          render :new, status: :unprocessable_entity
        end
      end
    
      private
    
      def plant_tag_params
        params.require(:plant_tag).permit(:tag)
      end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    def new
        @plant  = Plant.new
        @garden = Garden.find(params[:garden_id])
    end

    def create
        @plant  = Plant.new(plant_params)
        @garden = Garden.find(params[:garden_id])
        @plant.garden = @garden

        if @plant.save 
            redirect_to garden_path(@garden)
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def plant_params
        params.require(:plant).permit(:name, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<div class="container">
    <h1 class="mt-4">All Gardens</h1>

    <ul>
        <% @gardens.each do |garden| %>
            <li><%= link_to garden.name, garden_path(garden) %></li>
        <% end %>
    </ul>
</div>

app/views/gardens/show.html.erb
<div class="gardenBanner" id="banner" style="background-image: url(<%= @garden.image_url %>)">
    <i class="fa-solid fa-arrow-left" id="left"></i>
    <h1><%= @garden.name %></h1>
    <i class="fa-solid fa-arrow-right" id="right"></i>
</div>

<div class="container mt-3">
    <h3>The Plants</h3>
    <div class="plantFlex mt-2 pb-5">
        <% @plants.each do |plant| %>
            <div class="col-4 plantCard rounded" style="background-image: url(<%= plant.image_url %>)">
                <div>
                    <h4><%= plant.name %></p>
                    <div class="d-flex">
                        <% plant.tags.each do |tag| %>
                            <span><p><%= tag.name %>&nbsp;</p></span>
                        <% end %>
                        <div data-controller="form">
                            <p data-action="click->form#popUp" style="cursor: pointer;">➕</p>
                            <div class="hidden popUp" data-form-target="plantform">
                            <div class="formContainer">
                                <div class="text-center">
                                    <h1>Add Tag</h1>
                                    <%= simple_form_for [plant, @p_tag] do |f| %>
                                        <div class="d-flex flex-column">
                                            <div class="text-start d-flex flex-column">
                                                <%= f.collection_check_boxes :tag_id, Tag.all, :id, :name %>
                                            </div>
                                            <%= f.submit "Add!", class: "mt-4" %>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <%= link_to "➕🌴", new_garden_plant_path(@garden) %>
</div>

<%= render 'plant_tags/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WinterGarden</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/plant_tags/new.html.erb
<h3>Add a tag</h3>
<%= simple_form_for [ @garden, @plant, @p_tag ] do |f| %>
    <%= f.collection_check_boxes :tag_id, Tag.all, :id, :name %>
    <%= f.submit %>
<% end %>

app/views/plants/new.html.erb
<h1>Add a plant!</h1>
<%= simple_form_for [ @garden, @plant ] do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.submit %>
<% end %>